language: python

python:
  - 3.6

env:
  global:
    - PACKAGENAME="nbjekyll"

before_install:
  # Here we download miniconda and createour env
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda env create -f testenv.yml -v
  - source activate testenv
  - conda install -c conda-forge pygit2

install:
  - python setup.py install

script:
  - pytest $PACKAGENAME
