language: python

sudo: false

python:
  - 3.6

env:
  global:
    - PACKAGENAME="nbjekyll"

before_install:
  - bash get_conda.sh
  - conda create -f env testenv.yml
  - source activate testenv

install:
  - python setup.py install

script:
  - pytest $PACKAGENAME
