language: python

sudo: false

python:
  - 3.6

env:
  global:
    - PACKAGENAME="nbjekyll"

before_install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
- chmod +x miniconda.sh
- ./miniconda.sh -b -f -p $MINICONDA
- export PATH=/home/travis/miniconda/bin:$PATH
- conda config --set always_yes yes
- conda update --yes conda
- conda info -a
- conda create -f env ./testenv.yml
- source activate testenv

install:
- python setup.py install

script:
- pytest $PACKAGENAME
